
import { Country, Sector, ValuationMethod, AllTranslations, Currency } from './types';

export const APP_NAME = "ValuationPro";

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'US Dollar', nameAr: 'دولار أمريكي', symbol: '$' },
  { code: 'EUR', name: 'Euro', nameAr: 'يورو', symbol: '€' },
  { code: 'SAR', name: 'Saudi Riyal', nameAr: 'ريال سعودي', symbol: 'ر.س' },
  { code: 'AED', name: 'UAE Dirham', nameAr: 'درهم إماراتي', symbol: 'د.إ' },
  { code: 'EGP', name: 'Egyptian Pound', nameAr: 'جنيه مصري', symbol: 'ج.م' },
  { code: 'GBP', name: 'British Pound', nameAr: 'جنيه إسترليني', symbol: '£' },
];

export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States', nameAr: 'الولايات المتحدة', defaultCurrencyCode: 'USD' },
  { code: 'CA', name: 'Canada', nameAr: 'كندا', defaultCurrencyCode: 'CAD' }, // CAD not in CURRENCIES yet, add if needed or map to USD
  { code: 'GB', name: 'United Kingdom', nameAr: 'المملكة المتحدة', defaultCurrencyCode: 'GBP' },
  { code: 'DE', name: 'Germany', nameAr: 'ألمانيا', defaultCurrencyCode: 'EUR' },
  { code: 'FR', name: 'France', nameAr: 'فرنسا', defaultCurrencyCode: 'EUR' },
  { code: 'SA', name: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', defaultCurrencyCode: 'SAR' },
  { code: 'AE', name: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', defaultCurrencyCode: 'AED' },
  { code: 'EG', name: 'Egypt', nameAr: 'مصر', defaultCurrencyCode: 'EGP' },
];

export const SECTORS: Sector[] = [
  { id: 'tech', name: 'Technology', nameAr: 'التكنولوجيا' },
  { id: 'finance', name: 'Finance', nameAr: 'المالية' },
  { id: 'health', name: 'Healthcare', nameAr: 'الرعاية الصحية' },
  { id: 'consumer', name: 'Consumer Goods', nameAr: 'السلع الاستهلاكية' },
  { id: 'industrial', name: 'Industrial', nameAr: 'الصناعية' },
  { id: 'realestate', name: 'Real Estate', nameAr: 'العقارات' },
  { id: 'energy', name: 'Energy', nameAr: 'الطاقة' },
];

const defaultInputs: Array<'revenue' | 'ebitda' | 'netIncome' | 'totalAssets' | 'totalLiabilities' | 'benchmarkInputs'> = ['revenue', 'ebitda', 'netIncome', 'totalAssets', 'totalLiabilities', 'benchmarkInputs'];

export const VALUATION_METHODS: ValuationMethod[] = [
  { 
    id: 'dcf', 
    name: 'Discounted Cash Flow (DCF)', 
    nameAr: 'التدفقات النقدية المخصومة (DCF)',
    description: 'Estimates value based on projected future cash flows, discounted to present value. Requires detailed forecasts and assumptions about discount and growth rates. You can optionally input researched benchmarks like Country Risk Premium (to inform WACC) and Sector Growth Rate.',
    descriptionAr: 'تقدير القيمة بناءً على التدفقات النقدية المستقبلية المتوقعة، مخصومة إلى قيمتها الحالية. يتطلب توقعات مفصلة وافتراضات حول معدلات الخصم والنمو. يمكنك اختياريًا إدخال معايير بحثية مثل علاوة مخاطر الدولة (لإبلاغ المتوسط المرجح لتكلفة رأس المال) ومعدل نمو القطاع.',
    inputs: ['dcfSpecific', 'benchmarkInputs'] 
  },
  { 
    id: 'book', 
    name: 'Book Value', 
    nameAr: 'القيمة الدفترية',
    description: 'Calculates value based on the company\'s balance sheet (Assets - Liabilities). Often a baseline, may not reflect true market value.',
    descriptionAr: 'حساب القيمة بناءً على الميزانية العمومية للشركة (الأصول - الخصوم). غالبًا ما تكون قيمة أساسية، وقد لا تعكس القيمة السوقية الحقيقية.',
    inputs: ['totalAssets', 'totalLiabilities'] // No specific benchmarks here usually
  },
  { 
    id: 'comps', 
    name: 'Comparable Company Analysis (Comps)', 
    nameAr: 'تحليل الشركات المماثلة (Comps)',
    description: 'Values a company by comparing it to similar publicly traded companies using financial multiples. Input your researched average P/E or EV/EBITDA multiples for the relevant sector.',
    descriptionAr: 'تقييم الشركة بمقارنتها بشركات عامة مماثلة مدرجة في البورصة باستخدام المضاعفات المالية. أدخل متوسطات مضاعفات السعر إلى الأرباح أو قيمة المنشأة إلى الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك التي بحثت عنها للقطاع ذي الصلة.',
    inputs: ['netIncome', 'ebitda', 'benchmarkInputs'] // Requires financial metrics and benchmarks
  },
  { 
    id: 'multiples', 
    name: 'Market Multiples', 
    nameAr: 'مضاعفات السوق',
    description: 'Uses industry-average multiples applied to a key financial metric of the company. Input your researched average revenue multiple for the relevant sector.',
    descriptionAr: 'يستخدم متوسطات مضاعفات الصناعة المطبقة على مقياس مالي رئيسي للشركة. أدخل متوسط مضاعف الإيرادات الذي بحثت عنه للقطاع ذي الصلة.',
    inputs: ['revenue', 'benchmarkInputs'] // Requires financial metrics and benchmarks
  },
];

export const TRANSLATIONS: AllTranslations = {
  en: {
    appName: APP_NAME,
    nav: {
      home: 'Home',
      valuationForm: 'Valuation Tool',
      results: 'Results',
      about: 'About',
      help: 'Help/FAQ',
      language: 'Language',
      english: 'English',
      arabic: 'العربية',
      chart: 'Chart'
    },
    homePage: {
      title: 'Welcome to Company Valuation Platform',
      subtitle: 'Your partner for insightful estimations of non-listed company valuations, utilizing principles aligned with IFRS. Now with options to include your researched benchmarks!',
      ctaButton: 'Start Valuation',
      feature1Title: 'IFRS-Aligned Principles',
      feature1Desc: 'Valuation approaches considering International Financial Reporting Standards concepts.',
      feature2Title: 'Method-Specific Inputs & Benchmarks',
      feature2Desc: 'Tailored data inputs for different valuation methodologies like DCF, with options to add your own researched benchmarks.',
      feature3Title: 'Global & Sector Aware',
      feature3Desc: 'Considerations for multiple countries, currencies, and industry sectors. Enhance with your specific market data.',
      importantNotice: 'Important: This platform provides estimations for informational and educational purposes only. It is not a substitute for professional financial advice or certified valuation. The accuracy of valuations depends heavily on the data and benchmarks you provide. Consult with a qualified professional for critical decisions.',
    },
    valuationFormPage: {
      title: 'Company Valuation Form',
      companyDetails: 'Company Details',
      companyName: 'Company Name',
      companyNamePlaceholder: 'Enter company name',
      country: 'Country of Operation',
      selectCountry: 'Select Country',
      sector: 'Industry Sector',
      selectSector: 'Select Sector',
      currency: 'Reporting Currency',
      selectCurrency: 'Select Currency',
      valuationMethod: 'Valuation Method',
      selectMethod: 'Select Method',
      financialData: 'Financial Data (Annual)',
      revenue: 'Revenue (e.g., 1,000,000)',
      ebitda: 'EBITDA (e.g., 250,000)',
      netIncome: 'Net Income (e.g., 100,000)',
      totalAssets: 'Total Assets (e.g., 2,000,000)',
      totalLiabilities: 'Total Liabilities (e.g., 500,000)',
      dcfInputs: 'DCF Specific Inputs',
      projectionYears: 'Projection Horizon (Years, e.g., 3-5)',
      projectedFCFYear: 'Projected FCF - Year {year}',
      projectedFCFPlaceholder: 'Enter FCF for Year {year}',
      discountRate: 'Discount Rate (WACC, %, e.g., 10)',
      terminalGrowthRate: 'Terminal Growth Rate (%, e.g., 2)',
      // Benchmark Inputs
      benchmarkData: 'User-Provided Benchmarks (Optional)',
      benchmarkInfoTooltip: 'Input benchmarks you have researched from reliable sources. These can refine the valuation estimate.',
      userCountryRiskPremium: 'Country Risk Premium (%)',
      userCountryRiskPremiumPlaceholder: 'e.g., 2.5 (for WACC consideration)',
      userCountryRiskPremiumTooltip: 'A premium added to the risk-free rate to reflect the additional risk of investing in a specific country. Factor this into your WACC.',
      userSectorGrowthRate: 'Avg. Annual Sector Growth Rate (%)',
      userSectorGrowthRatePlaceholder: 'e.g., 4 (for FCF/Terminal Growth)',
      userSectorGrowthRateTooltip: 'The expected average annual growth rate for the company\'s sector. Can inform FCF projections or terminal growth rate if specific company projections are unavailable.',
      userIndustryPERatio: 'Avg. Industry P/E Ratio',
      userIndustryPERatioPlaceholder: 'e.g., 15 (for Comps)',
      userIndustryPERatioTooltip: 'Average Price-to-Earnings ratio for comparable companies in the industry. Used with Net Income.',
      userIndustryEVEBITDAMultiple: 'Avg. Industry EV/EBITDA Multiple',
      userIndustryEVEBITDAMultiplePlaceholder: 'e.g., 8 (for Comps)',
      userIndustryEVEBITDAMultipleTooltip: 'Average Enterprise Value to EBITDA multiple for comparable companies. Used with EBITDA.',
      userIndustryRevenueMultiple: 'Avg. Industry Revenue Multiple',
      userIndustryRevenueMultiplePlaceholder: 'e.g., 1.2 (for Market Multiples)',
      userIndustryRevenueMultipleTooltip: 'Average Enterprise Value to Revenue multiple for the industry. Used with Revenue.',
      submit: 'Calculate Valuation',
      calculating: 'Calculating...',
      error: 'An error occurred. Please try again.',
      errorFillFields: 'Please fill in all required company details, select a method, and provide necessary financial inputs. Ensure all numbers are valid.',
      errorInvalidNumber: 'Please enter valid numbers for financial data and benchmarks.',
    },
    resultsPage: {
      title: 'Valuation Results',
      noResults: 'No valuation data found. Please complete the form first.',
      backToForm: 'Go to Valuation Form',
      companyName: 'Company Name:',
      country: 'Country:',
      sector: 'Sector:',
      currency: 'Currency:',
      valuationMethod: 'Valuation Method:',
      estimatedValue: 'Estimated Valuation:',
      summary: 'Summary & Assumptions',
      downloadReport: 'Download Report (.pdf)',
      printReport: 'Print Report',
      ifrsComplianceNote: 'Disclaimer: This valuation is an estimate based on the provided data and selected methodology, aligned with general IFRS principles. It is for informational purposes and should not be considered a certified valuation or financial advice. The accuracy is highly dependent on the quality of your inputs and any benchmarks you provided. Consult with a qualified professional for any investment or strategic decisions.',
      dcfInputsTitle: 'Key DCF Inputs Used:',
      dcfProjectionYears: 'Projection Years:',
      dcfDiscountRate: 'Discount Rate (WACC):',
      dcfTerminalGrowthRate: 'Terminal Growth Rate:',
      benchmarksUsedTitle: 'User-Provided Benchmarks Used:',
      benchmarksNotUsed: 'No specific user benchmarks were applied to this calculation beyond standard inputs.',
      userCountryRiskPremium: 'Country Risk Premium Input:',
      userSectorGrowthRate: 'Sector Growth Rate Input:',
      userIndustryPERatio: 'Industry P/E Ratio Input:',
      userIndustryEVEBITDAMultiple: 'Industry EV/EBITDA Multiple Input:',
      userIndustryRevenueMultiple: 'Industry Revenue Multiple Input:',
      calculationDetails: {
        title: "Calculation Breakdown",
        introduction: "The estimated valuation was derived using the {methodName} method as follows. Financial figures and assumptions are based on user-provided data.",
        dataSourceNote: "\nNote on Data: Core financial figures (revenue, EBITDA, assets, FCFs, WACC, etc.) and any specific benchmarks (e.g., industry multiples, risk premiums) are based on data entered by the user. This platform does not automatically fetch or verify external market data or benchmarks. The quality of the valuation is directly dependent on the accuracy and appropriateness of these inputs.",
        dcf: {
          intro: "The Discounted Cash Flow (DCF) model involves projecting future free cash flows (FCFs) and discounting them back to their present value.",
          waccExplanationTitle: "Understanding WACC (Weighted Average Cost of Capital):",
          waccExplanation: "WACC represents a company's average after-tax cost of capital from all sources. It's used as the discount rate. Your WACC input should ideally consider factors like the risk-free rate, market risk premium, company beta, cost of debt, and any applicable country risk premium (you can input a researched Country Risk Premium separately to inform this).",
          fcfExplanationTitle: "Understanding FCF (Free Cash Flow):",
          fcfExplanation: "FCF is the cash available to all investors after operating and capital expenditures. Your FCF projections are key. An optional user-input 'Avg. Annual Sector Growth Rate' can inform terminal growth if not directly specified.",
          inputsHeader: "Key Inputs (User-Provided):",
          fcfList: "Projected FCFs:",
          fcfYear: "Year {year}: {value}",
          wacc: "Discount Rate (WACC): {value}%",
          terminalGrowth: "Terminal Growth Rate: {value}%",
          projectionPeriod: "Projection Period: {value} years",
          userSectorGrowthRateUsed: "User-provided Sector Growth Rate of {value}% was considered for terminal growth.",
          step1Header: "Step 1: Calculate Present Value (PV) of Projected FCFs",
          step1Desc: "Each year's FCF is discounted using the WACC. The sum of these PVs is {pvSum}.",
          pvFcfCalc: "PV(FCF Year {year}) = {fcf} / (1 + {waccDecimal})^{year} = {pvFcf}",
          step2Header: "Step 2: Calculate Terminal Value (TV)",
          step2Desc: "The value of the company beyond the projection period is estimated. Last projected FCF used: {lastFcf}.",
          tvGGM: "TV (Gordon Growth Model) = ({lastFcf} * (1 + {terminalGrowthDecimal})) / ({waccDecimal} - {terminalGrowthDecimal}) = {tv}",
          tvFallback: "TV (Fallback Multiple of last FCF as WACC <= Terminal Growth) = {lastFcf} * 10 = {tv}",
          step3Header: "Step 3: Calculate Present Value (PV) of Terminal Value",
          step3Desc: "The TV is discounted back to the present: PV(TV) = {tv} / (1 + {waccDecimal})^{projectionYears} = {pvTv}",
          step4Header: "Step 4: Calculate Enterprise Value (EV)",
          step4Desc: "EV = Sum of PV of Projected FCFs + PV of TV = {pvSum} + {pvTv} = {ev}",
          step5Header: "Step 5: Apply Liquidity Discount (for non-listed companies)",
          step5Desc: "A {discountPercentage}% liquidity discount is applied: EV * {discountFactor} = {discountedEv}",
          step6Header: "Step 6: Final Estimated Value",
          step6Desc: "The final estimated value is {finalValue}.",
          minValNote: "Note: A minimum valuation threshold was applied."
        },
        book: {
          intro: "The Book Value method calculates equity based on the company's balance sheet.",
          inputsHeader: "Key Inputs (User-Provided):",
          totalAssets: "Total Assets: {value}",
          totalLiabilities: "Total Liabilities: {value}",
          step1Header: "Step 1: Calculate Book Value of Equity",
          step1Desc: "Book Value = Total Assets - Total Liabilities = {totalAssets} - {totalLiabilities} = {bookValue}",
          step2Header: "Step 2: Final Estimated Value",
          step2Desc: "The final estimated value is {finalValue}.",
          minValNote: "Note: A minimum valuation threshold was applied."
        },
        other: { 
          intro: "This method uses a financial metric from the company and applies a multiplier. If you provided a specific industry benchmark multiple, it's used here.",
          inputsHeader: "Key Inputs (User-Provided):",
          revenue: "Revenue: {value}",
          ebitda: "EBITDA: {value}",
          netIncome: "Net Income: {value}",
          step1Header: "Step 1: Identify Base Financial Metric & Multiplier",
          step1DescCompsPE: "Base: Net Income = {netIncome}. User-provided P/E Ratio: {peRatio}.",
          step1DescCompsEVEBITDA: "Base: EBITDA = {ebitda}. User-provided EV/EBITDA Multiple: {evEbitdaMultiple}.",
          step1DescMultiplesRevenue: "Base: Revenue = {revenue}. User-provided Revenue Multiple: {revMultiple}.",
          step1DescGeneric: "Base Value derived from Revenue & EBITDA minus Liabilities = {baseValue}. Generic Multiplier: {multiplier}.",
          step2Header: "Step 2: Calculate Estimated Value",
          step2DescCompsPE: "Estimated Value = Net Income * P/E Ratio = {netIncome} * {peRatio} = {estimatedValue}",
          step2DescCompsEVEBITDA: "Estimated Value (EV) = EBITDA * EV/EBITDA Multiple = {ebitda} * {evEbitdaMultiple} = {estimatedValue}",
          step2DescMultiplesRevenue: "Estimated Value (EV) = Revenue * Revenue Multiple = {revenue} * {revMultiple} = {estimatedValue}",
          step2DescGeneric: "Estimated Value = Base Value * Multiplier = {baseValue} * {multiplier} = {estimatedValue}",
          step3Header: "Step 3: Final Estimated Value (after adjustments/thresholds)",
          step3Desc: "The final estimated value is {finalValue}.",
          minValNote: "Note: A minimum valuation threshold was applied."
        }
      }
    },
    aboutPage: {
      title: 'About Our Platform',
      p1: 'This platform provides tools for estimating the valuation of non-listed companies using methodologies that align with the principles of IFRS. Our goal is to offer accessible and insightful valuation estimates for educational and preliminary analytical purposes. You can enhance these estimates by inputting your own researched financial benchmarks.',
      p2: 'We support various valuation methods, allowing users to select an appropriate approach and input relevant data, including optional market benchmarks. The platform is designed for entrepreneurs, students, investors, and financial analysts looking for initial valuation insights.',
      ifrsTitle: 'IFRS Principles Alignment',
      ifrsDesc: 'Our calculations and method explanations aim to adhere to IFRS principles, such as Fair Value Measurement (IFRS 13), promoting transparency and comparability. However, these are high-level estimates and do not constitute a formal IFRS-compliant valuation, which would require significantly more detailed analysis, data, and professional judgment. Users are responsible for understanding the limitations.',
      methodsTitle: 'Valuation Methods',
      methodsDesc: 'We offer a range of methods. Each method has its specific data requirements, assumptions, and is suited for different scenarios. Detailed descriptions are provided with each method selection.',
      dataSensitivity: 'Data Sensitivity & Accuracy',
      dataSensitivityDesc: 'The accuracy of the valuation is highly dependent on the quality and accuracy of the data you provide, including any financial benchmarks you enter. Ensure your inputs are as realistic and well-researched as possible. Small changes in key assumptions (like discount rates, growth rates, or market multiples) can significantly impact the final valuation.',
      professionalAdvice: 'Seek Professional Advice',
      professionalAdviceDesc: 'The valuations generated by this platform are for informational purposes only. They should not be used as the sole basis for making financial, investment, or strategic decisions. Always consult with a qualified financial advisor or valuation expert for comprehensive analysis and certified valuations.',
      benchmarkingTitle: 'Using Financial Benchmarks',
      benchmarkingDesc: "This platform allows you to optionally input financial benchmarks (e.g., industry multiples, country risk premiums, sector growth rates) that you have researched from external sources. This can help refine the valuation estimates. However, the platform does not automatically fetch or verify these benchmarks. The responsibility for finding accurate and appropriate benchmarks rests with you. Consider sources like:\n- Reputable financial data providers (some offer limited free data or reports).\n- Academic research (e.g., Damodaran Online for country risk premiums and other data).\n- Official government statistics and central bank reports.\n- Detailed industry analysis reports from major consulting firms, investment banks, or industry associations.\nAlways critically assess the source, date, and applicability of any benchmark data to the specific company being valued."
    },
    helpPage: {
      title: 'Help & Frequently Asked Questions',
      q1_q: 'What is company valuation?',
      q1_a: 'Company valuation is the process of determining the economic worth of a business or company. It can be used for various purposes, such as M&A, fundraising, financial reporting, or strategic planning.',
      q2_q: 'How does this platform align with IFRS?',
      q2_a: 'The platform incorporates valuation principles and methodologies consistent with general IFRS guidelines (e.g., concepts from IFRS 13 Fair Value Measurement). However, it is a simplified tool and does not perform a full IFRS-compliant valuation. Always refer to official standards and seek professional advice for formal reporting.',
      q3_q: 'Which valuation method should I choose?',
      q3_a: 'The choice depends on the company\'s stage, industry, data availability, and purpose. DCF is often for stable businesses. Comparables are useful with similar public companies. Our descriptions offer brief guidance. For critical decisions, consult a professional.',
      q4_q: 'Are the results definitive or certified?',
      q4_a: 'No. Results are estimates based on your data and chosen method. They are for informational/educational purposes ONLY. Market conditions and specifics greatly influence actual valuations.',
      q5_q: 'Can I save or export my valuation?',
      q5_a: 'The results page offers options to download a PDF summary or print the report. Full data saving to an account is not currently implemented.',
      q6_q: 'What are the key assumptions in DCF?',
      q6_a: 'Key DCF assumptions include projected Free Cash Flows (FCFs), the Discount Rate (WACC - which should reflect country and company-specific risks), and the Terminal Growth Rate. You can input a researched Country Risk Premium to inform your WACC and an Avg. Sector Growth Rate to inform projections or terminal value.',
      q7_q: 'Where can I find financial benchmarks?',
      q7_a: "This platform allows you to input benchmarks you've researched. For reliable sources, consider:\n- Financial data providers (e.g., Refinitiv, Bloomberg, FactSet often have free summaries or trial access).\n- Academic resources like Aswath Damodaran's website (pages.stern.nyu.edu/~adamodar/) for data on risk premiums, betas, etc.\n- Reports from major investment banks, consulting firms (e.g., PwC, Deloitte, EY, McKinsey), and industry associations.\n- Government statistical agencies and central banks for economic data and country risk assessments.\nAlways check the data's relevance, date, and methodology. The platform does not fetch this data automatically.",
      q8_q: 'How are user-provided benchmarks used?',
      q8_a: 'If you input benchmarks like average industry P/E ratios, EV/EBITDA multiples, or sector growth rates, the platform will attempt to use them in the relevant valuation method (e.g., P/E in Comparables, sector growth in DCF terminal value if applicable). The calculation breakdown in your results will detail how any provided benchmarks were incorporated. If not provided, the platform may use more generic assumptions for its mock calculations.',
    },
    footer: {
      copyright: `© ${new Date().getFullYear()} ${APP_NAME}. All rights reserved. For educational & demonstration purposes only.`,
      contactName: 'Name: Yaser Ali',
      contactMobile: 'Mob: +966591715184',
      contactEmail: 'E-mail: y_ali41@hotmail.com',
      contactLinkedIn: 'www.linkedin.com/in/yaser-yousef-ali',
      contactLinkedInUrl: 'https://www.linkedin.com/in/yaser-yousef-ali'
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      noData: 'No data available',
      selectOption: 'Select an option',
      details: 'Details',
      years: 'Years',
      percentageSymbol: '%',
    }
  },
  ar: {
    appName: APP_NAME,
    nav: {
      home: 'الرئيسية',
      valuationForm: 'أداة التقييم',
      results: 'النتائج',
      about: 'عنا',
      help: 'المساعدة/الأسئلة الشائعة',
      language: 'اللغة',
      english: 'English',
      arabic: 'العربية',
      chart: 'الرسم البياني'
    },
    homePage: {
      title: 'مرحبًا بك في منصة تقييم الشركات',
      subtitle: 'شريكك للحصول على تقديرات معمقة لتقييمات الشركات غير المدرجة، باستخدام مبادئ متوافقة مع المعايير الدولية لإعداد التقارير المالية. الآن مع خيارات لتضمين معاييرك البحثية!',
      ctaButton: 'ابدأ التقييم',
      feature1Title: 'مبادئ متوافقة مع IFRS',
      feature1Desc: 'نهج تقييم تأخذ في الاعتبار مفاهيم المعايير الدولية لإعداد التقارير المالية.',
      feature2Title: 'مدخلات ومعايير خاصة بالطريقة',
      feature2Desc: 'مدخلات بيانات مخصصة لمنهجيات التقييم المختلفة مثل التدفقات النقدية المخصومة، مع خيارات لإضافة معاييرك البحثية الخاصة.',
      feature3Title: 'وعي عالمي وقطاعي',
      feature3Desc: 'اعتبارات لبلدان وعملات وقطاعات صناعية متعددة. عززها ببيانات السوق المحددة الخاصة بك.',
      importantNotice: 'هام: توفر هذه المنصة تقديرات للأغراض المعلوماتية والتعليمية فقط. إنها ليست بديلاً عن المشورة المالية المتخصصة أو التقييم المعتمد. تعتمد دقة التقييمات بشكل كبير على البيانات والمعايير التي تقدمها. استشر متخصصًا مؤهلاً لاتخاذ القرارات الحاسمة.',
    },
    valuationFormPage: {
      title: 'نموذج تقييم الشركة',
      companyDetails: 'تفاصيل الشركة',
      companyName: 'اسم الشركة',
      companyNamePlaceholder: 'أدخل اسم الشركة',
      country: 'بلد التشغيل',
      selectCountry: 'اختر البلد',
      sector: 'قطاع الصناعة',
      selectSector: 'اختر القطاع',
      currency: 'عملة التقرير',
      selectCurrency: 'اختر العملة',
      valuationMethod: 'طريقة التقييم',
      selectMethod: 'اختر الطريقة',
      financialData: 'البيانات المالية (سنوية)',
      revenue: 'الإيرادات (مثال: 1,000,000)',
      ebitda: 'الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك (مثال: 250,000)',
      netIncome: 'صافي الدخل (مثال: 100,000)',
      totalAssets: 'إجمالي الأصول (مثال: 2,000,000)',
      totalLiabilities: 'إجمالي الخصوم (مثال: 500,000)',
      dcfInputs: 'مدخلات خاصة بالتدفقات النقدية المخصومة',
      projectionYears: 'أفق التوقع (سنوات، مثال: 3-5)',
      projectedFCFYear: 'التدفق النقدي الحر المتوقع - سنة {year}',
      projectedFCFPlaceholder: 'أدخل التدفق النقدي الحر للسنة {year}',
      discountRate: 'معدل الخصم (WACC، %، مثال: 10)',
      terminalGrowthRate: 'معدل النمو النهائي (٪، مثال: 2)',
      // Benchmark Inputs - Arabic
      benchmarkData: 'المعايير المقدمة من المستخدم (اختياري)',
      benchmarkInfoTooltip: 'أدخل المعايير التي بحثت عنها من مصادر موثوقة. يمكن أن تساعد في تحسين تقدير التقييم.',
      userCountryRiskPremium: 'علاوة مخاطر الدولة (%)',
      userCountryRiskPremiumPlaceholder: 'مثال: 2.5 (لاحتساب WACC)',
      userCountryRiskPremiumTooltip: 'علاوة تضاف إلى معدل العائد الخالي من المخاطر لتعكس المخاطر الإضافية للاستثمار في بلد معين. ضع هذا في اعتبارك عند تحديد WACC الخاص بك.',
      userSectorGrowthRate: 'متوسط معدل النمو السنوي للقطاع (%)',
      userSectorGrowthRatePlaceholder: 'مثال: 4 (للتدفقات النقدية الحرة/النمو النهائي)',
      userSectorGrowthRateTooltip: 'متوسط معدل النمو السنوي المتوقع لقطاع الشركة. يمكن أن يفيد توقعات التدفق النقدي الحر أو معدل النمو النهائي إذا كانت توقعات الشركة المحددة غير متوفرة.',
      userIndustryPERatio: 'متوسط مضاعف السعر إلى الأرباح للصناعة',
      userIndustryPERatioPlaceholder: 'مثال: 15 (للمقارنات)',
      userIndustryPERatioTooltip: 'متوسط مضاعف السعر إلى الأرباح للشركات المماثلة في الصناعة. يستخدم مع صافي الدخل.',
      userIndustryEVEBITDAMultiple: 'متوسط مضاعف قيمة المنشأة/الأرباح قبل الفوائد والضرائب للقطاع',
      userIndustryEVEBITDAMultiplePlaceholder: 'مثال: 8 (للمقارنات)',
      userIndustryEVEBITDAMultipleTooltip: 'متوسط مضاعف قيمة المنشأة إلى الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك للشركات المماثلة. يستخدم مع الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك.',
      userIndustryRevenueMultiple: 'متوسط مضاعف الإيرادات للصناعة',
      userIndustryRevenueMultiplePlaceholder: 'مثال: 1.2 (لمضاعفات السوق)',
      userIndustryRevenueMultipleTooltip: 'متوسط مضاعف قيمة المنشأة إلى الإيرادات للصناعة. يستخدم مع الإيرادات.',
      submit: 'احسب التقييم',
      calculating: 'جارٍ الحساب...',
      error: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
      errorFillFields: 'يرجى ملء جميع تفاصيل الشركة المطلوبة، واختيار طريقة، وتقديم المدخلات المالية اللازمة. تأكد من أن جميع الأرقام صالحة.',
      errorInvalidNumber: 'يرجى إدخال أرقام صالحة للبيانات المالية والمعايير.',
    },
    resultsPage: {
      title: 'نتائج التقييم',
      noResults: 'لم يتم العثور على بيانات تقييم. يرجى إكمال النموذج أولاً.',
      backToForm: 'العودة إلى نموذج التقييم',
      companyName: 'اسم الشركة:',
      country: 'البلد:',
      sector: 'القطاع:',
      currency: 'العملة:',
      valuationMethod: 'طريقة التقييم:',
      estimatedValue: 'التقييم المقدر:',
      summary: 'الملخص والافتراضات',
      downloadReport: 'تنزيل التقرير (pdf.)',
      printReport: 'طباعة التقرير',
      ifrsComplianceNote: 'إخلاء مسؤولية: هذا التقييم هو تقدير يستند إلى البيانات المقدمة والمنهجية المختارة، ويتماشى مع مبادئ IFRS العامة. إنه للأغراض المعلوماتية ولا ينبغي اعتباره تقييمًا معتمدًا أو مشورة مالية. تعتمد الدقة بشكل كبير على جودة مدخلاتك وأي معايير قدمتها. استشر متخصصًا مؤهلاً لأي قرارات استثمارية أو استراتيجية.',
      dcfInputsTitle: 'مدخلات DCF الرئيسية المستخدمة:',
      dcfProjectionYears: 'سنوات الإسقاط:',
      dcfDiscountRate: 'معدل الخصم (WACC):',
      dcfTerminalGrowthRate: 'معدل النمو النهائي:',
      benchmarksUsedTitle: 'المعايير المقدمة من المستخدم والمستخدمة:',
      benchmarksNotUsed: 'لم يتم تطبيق أي معايير مستخدم محددة على هذا الحساب بخلاف المدخلات القياسية.',
      userCountryRiskPremium: 'مدخل علاوة مخاطر الدولة:',
      userSectorGrowthRate: 'مدخل معدل نمو القطاع:',
      userIndustryPERatio: 'مدخل مضاعف السعر إلى الأرباح للصناعة:',
      userIndustryEVEBITDAMultiple: 'مدخل مضاعف قيمة المنشأة/الأرباح للقطاع:',
      userIndustryRevenueMultiple: 'مدخل مضاعف الإيرادات للصناعة:',
      calculationDetails: {
        title: "تفاصيل الحساب",
        introduction: "تم اشتقاق القيمة التقديرية باستخدام طريقة {methodName} كما يلي. تستند الأرقام والافتراضات المالية إلى البيانات المقدمة من المستخدم.",
        dataSourceNote: "\nملاحظة حول البيانات: تستند الأرقام المالية الأساسية (الإيرادات، الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك، الأصول، التدفقات النقدية الحرة، المتوسط المرجح لتكلفة رأس المال، إلخ) وأي معايير محددة (مثل مضاعفات الصناعة، علاوات المخاطر) إلى البيانات التي أدخلها المستخدم. لا تقوم هذه المنصة تلقائيًا بجلب أو التحقق من بيانات السوق الخارجية أو المعايير. تعتمد جودة التقييم بشكل مباشر على دقة وملاءمة هذه المدخلات.",
        dcf: {
          intro: "يتضمن نموذج التدفقات النقدية المخصومة (DCF) توقع التدفقات النقدية الحرة المستقبلية (FCFs) وخصمها إلى قيمتها الحالية.",
          waccExplanationTitle: "فهم WACC (المتوسط المرجح لتكلفة رأس المال):",
          waccExplanation: "يمثل المتوسط المرجح لتكلفة رأس المال (WACC) متوسط تكلفة رأس مال الشركة بعد الضريبة من جميع المصادر. يُستخدم كمعدل خصم. يجب أن يأخذ مدخل WACC الخاص بك في الاعتبار بشكل مثالي عوامل مثل معدل العائد الخالي من المخاطر، وعلاوة مخاطر السوق، وبيتا الشركة، وتكلفة الدين، وأي علاوة مخاطر دولة مطبقة (يمكنك إدخال علاوة مخاطر دولة بحثت عنها بشكل منفصل لإبلاغ هذا).",
          fcfExplanationTitle: "فهم FCF (التدفق النقدي الحر):",
          fcfExplanation: "التدفق النقدي الحر (FCF) هو النقد المتاح لجميع المستثمرين بعد نفقات التشغيل والرأسمالية. توقعات FCF الخاصة بك هي المفتاح. يمكن لمدخل اختياري من المستخدم 'متوسط معدل النمو السنوي للقطاع' أن يفيد النمو النهائي إذا لم يتم تحديده مباشرة.",
          inputsHeader: "المدخلات الرئيسية (مقدمة من المستخدم):",
          fcfList: "التدفقات النقدية الحرة المتوقعة:",
          fcfYear: "السنة {year}: {value}",
          wacc: "معدل الخصم (WACC): {value}%",
          terminalGrowth: "معدل النمو النهائي: {value}%",
          projectionPeriod: "فترة التوقع: {value} سنوات",
          userSectorGrowthRateUsed: "تم اعتبار معدل نمو القطاع المقدم من المستخدم بنسبة {value}% للنمو النهائي.",
          step1Header: "الخطوة 1: حساب القيمة الحالية (PV) للتدفقات النقدية الحرة المتوقعة",
          step1Desc: "يتم خصم التدفق النقدي الحر لكل سنة باستخدام معدل الخصم (WACC). مجموع هذه القيم الحالية هو {pvSum}.",
          pvFcfCalc: "القيمة الحالية (FCF السنة {year}) = {fcf} / (1 + {waccDecimal})^{year} = {pvFcf}",
          step2Header: "الخطوة 2: حساب القيمة النهائية (TV)",
          step2Desc: "يتم تقدير قيمة الشركة بعد فترة التوقع. آخر تدفق نقدي حر متوقع مستخدم: {lastFcf}.",
          tvGGM: "القيمة النهائية (نموذج جوردون للنمو) = ({lastFcf} * (1 + {terminalGrowthDecimal})) / ({waccDecimal} - {terminalGrowthDecimal}) = {tv}",
          tvFallback: "القيمة النهائية (مضاعف احتياطي لآخر FCF لأن WACC <= معدل النمو النهائي) = {lastFcf} * 10 = {tv}",
          step3Header: "الخطوة 3: حساب القيمة الحالية (PV) للقيمة النهائية",
          step3Desc: "يتم خصم القيمة النهائية إلى القيمة الحالية: القيمة الحالية (TV) = {tv} / (1 + {waccDecimal})^{projectionYears} = {pvTv}",
          step4Header: "الخطوة 4: حساب قيمة المنشأة (EV)",
          step4Desc: "قيمة المنشأة = مجموع القيمة الحالية للتدفقات النقدية الحرة المتوقعة + القيمة الحالية للقيمة النهائية = {pvSum} + {pvTv} = {ev}",
          step5Header: "الخطوة 5: تطبيق خصم السيولة (للشركات غير المدرجة)",
          step5Desc: "يتم تطبيق خصم سيولة بنسبة {discountPercentage}%: قيمة المنشأة * {discountFactor} = {discountedEv}",
          step6Header: "الخطوة 6: القيمة التقديرية النهائية",
          step6Desc: "القيمة التقديرية النهائية هي {finalValue}.",
          minValNote: "ملاحظة: تم تطبيق حد أدنى للتقييم."
        },
        book: {
          intro: "تحسب طريقة القيمة الدفترية حقوق الملكية بناءً على الميزانية العمومية للشركة.",
          inputsHeader: "المدخلات الرئيسية (مقدمة من المستخدم):",
          totalAssets: "إجمالي الأصول: {value}",
          totalLiabilities: "إجمالي الخصوم: {value}",
          step1Header: "الخطوة 1: حساب القيمة الدفترية لحقوق الملكية",
          step1Desc: "القيمة الدفترية = إجمالي الأصول - إجمالي الخصوم = {totalAssets} - {totalLiabilities} = {bookValue}",
          step2Header: "الخطوة 2: القيمة التقديرية النهائية",
          step2Desc: "القيمة التقديرية النهائية هي {finalValue}.",
          minValNote: "ملاحظة: تم تطبيق حد أدنى للتقييم."
        },
        other: {
          intro: "تستخدم هذه الطريقة مقياسًا ماليًا من الشركة وتطبق مضاعفًا. إذا قدمت مضاعف صناعة معياري محدد، فسيتم استخدامه هنا.",
          inputsHeader: "المدخلات الرئيسية (مقدمة من المستخدم):",
          revenue: "الإيرادات: {value}",
          ebitda: "الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك: {value}",
          netIncome: "صافي الدخل: {value}",
          step1Header: "الخطوة 1: تحديد المقياس المالي الأساسي والمضاعف",
          step1DescCompsPE: "الأساس: صافي الدخل = {netIncome}. مضاعف السعر إلى الأرباح المقدم من المستخدم: {peRatio}.",
          step1DescCompsEVEBITDA: "الأساس: الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك = {ebitda}. مضاعف قيمة المنشأة/الأرباح قبل الفوائد والضرائب المقدم من المستخدم: {evEbitdaMultiple}.",
          step1DescMultiplesRevenue: "الأساس: الإيرادات = {revenue}. مضاعف الإيرادات المقدم من المستخدم: {revMultiple}.",
          step1DescGeneric: "القيمة الأساسية المشتقة من الإيرادات والأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك ناقص الخصوم = {baseValue}. مضاعف عام: {multiplier}.",
          step2Header: "الخطوة 2: حساب القيمة المقدرة",
          step2DescCompsPE: "القيمة المقدرة = صافي الدخل * مضاعف السعر إلى الأرباح = {netIncome} * {peRatio} = {estimatedValue}",
          step2DescCompsEVEBITDA: "القيمة المقدرة (قيمة المنشأة) = الأرباح قبل الفوائد والضرائب والإهلاك والاستهلاك * مضاعف قيمة المنشأة/الأرباح = {ebitda} * {evEbitdaMultiple} = {estimatedValue}",
          step2DescMultiplesRevenue: "القيمة المقدرة (قيمة المنشأة) = الإيرادات * مضاعف الإيرادات = {revenue} * {revMultiple} = {estimatedValue}",
          step2DescGeneric: "القيمة المقدرة = القيمة الأساسية * المضاعف = {baseValue} * {multiplier} = {estimatedValue}",
          step3Header: "الخطوة 3: القيمة التقديرية النهائية (بعد التعديلات/الحدود الدنيا)",
          step3Desc: "القيمة التقديرية النهائية هي {finalValue}.",
          minValNote: "ملاحظة: تم تطبيق حد أدنى للتقييم."
        }
      }
    },
    aboutPage: {
      title: 'عن منصتنا',
      p1: 'توفر هذه المنصة أدوات لتقدير تقييم الشركات غير المدرجة باستخدام منهجيات تتماشى مع مبادئ المعايير الدولية لإعداد التقارير المالية. هدفنا هو تقديم تقديرات تقييم سهلة الوصول ومفيدة للأغراض التعليمية والتحليلية الأولية. يمكنك تحسين هذه التقديرات بإدخال معاييرك المالية البحثية الخاصة.',
      p2: 'نحن ندعم طرق تقييم متنوعة، مما يسمح للمستخدمين باختيار النهج المناسب وإدخال البيانات ذات الصلة، بما في ذلك معايير السوق الاختيارية. تم تصميم المنصة لرواد الأعمال والطلاب والمستثمرين والمحللين الماليين الذين يبحثون عن رؤى تقييم أولية.',
      ifrsTitle: 'التوافق مع مبادئ IFRS',
      ifrsDesc: 'تهدف حساباتنا وشروحات الطرق إلى الالتزام بمبادئ المعايير الدولية لإعداد التقارير المالية، مثل قياس القيمة العادلة (IFRS 13)، مما يعزز الشفافية وقابلية المقارنة. ومع ذلك، فهذه تقديرات عالية المستوى ولا تشكل تقييمًا رسميًا متوافقًا مع IFRS، الأمر الذي يتطلب تحليلاً وبيانات وحكمًا مهنيًا أكثر تفصيلاً بكثير. المستخدمون مسؤولون عن فهم القيود.',
      methodsTitle: 'طرق التقييم',
      methodsDesc: 'نحن نقدم مجموعة من الطرق. كل طريقة لها متطلبات بيانات وافتراضات محددة، وهي مناسبة لسيناريوهات مختلفة. يتم توفير أوصاف مفصلة مع اختيار كل طريقة.',
      dataSensitivity: 'حساسية البيانات ودقتها',
      dataSensitivityDesc: 'تعتمد دقة التقييم بشكل كبير على جودة ودقة البيانات التي تقدمها، بما في ذلك أي معايير مالية تدخلها. تأكد من أن مدخلاتك واقعية ومدروسة قدر الإمكان. يمكن للتغييرات الصغيرة في الافتراضات الرئيسية (مثل معدلات الخصم أو معدلات النمو أو مضاعفات السوق) أن تؤثر بشكل كبير على التقييم النهائي.',
      professionalAdvice: 'اطلب مشورة متخصصة',
      professionalAdviceDesc: 'التقييمات التي تم إنشاؤها بواسطة هذه المنصة هي للأغراض المعلوماتية فقط. لا ينبغي استخدامها كأساس وحيد لاتخاذ القرارات المالية أو الاستثمارية أو الاستراتيجية. استشر دائمًا مستشارًا ماليًا مؤهلاً أو خبير تقييم لإجراء تحليل شامل وتقييمات معتمدة.',
      benchmarkingTitle: 'استخدام المعايير المالية',
      benchmarkingDesc: "تتيح لك هذه المنصة إدخال معايير مالية بشكل اختياري (مثل مضاعفات الصناعة، علاوات مخاطر الدولة، معدلات نمو القطاع) التي بحثت عنها من مصادر خارجية. يمكن أن يساعد هذا في تحسين تقديرات التقييم. ومع ذلك، لا تقوم المنصة تلقائيًا بجلب أو التحقق من هذه المعايير. تقع مسؤولية العثور على معايير دقيقة ومناسبة على عاتقك. ضع في اعتبارك مصادر مثل:\n- مزودي البيانات المالية ذوي السمعة الطيبة (يقدم البعض بيانات أو تقارير مجانية محدودة).\n- الأبحاث الأكاديمية (مثل Damodaran Online لعلاوات مخاطر الدولة وبيانات أخرى).\n- الإحصاءات الحكومية الرسمية وتقارير البنوك المركزية.\n- تقارير تحليل الصناعة المفصلة من كبرى الشركات الاستشارية أو البنوك الاستثمارية أو جمعيات الصناعة.\nقم دائمًا بتقييم مصدر البيانات وتاريخها ومدى ملاءمتها بشكل نقدي للشركة المحددة التي يتم تقييمها."
    },
    helpPage: {
      title: 'المساعدة والأسئلة الشائعة',
      q1_q: 'ما هو تقييم الشركة؟',
      q1_a: 'تقييم الشركة هو عملية تحديد القيمة الاقتصادية لعمل أو شركة. يمكن استخدامه لأغراض مختلفة، مثل عمليات الاندماج والاستحواذ، أو جمع الأموال، أو إعداد التقارير المالية، أو التخطيط الاستراتيجي.',
      q2_q: 'كيف تتماشى هذه المنصة مع المعايير الدولية لإعداد التقارير المالية؟',
      q2_a: 'تتضمن المنصة مبادئ ومنهجيات تقييم تتفق مع إرشادات IFRS العامة. ومع ذلك، فهي أداة مبسطة ولا تقوم بتقييم كامل متوافق مع IFRS. ارجع دائمًا إلى المعايير الرسمية واطلب المشورة المهنية.',
      q3_q: 'أي طريقة تقييم يجب أن أختار؟',
      q3_a: 'يعتمد الاختيار على مرحلة الشركة، والصناعة، وتوافر البيانات، والغرض. DCF غالبًا للشركات المستقرة. المقارنات مفيدة مع الشركات العامة المماثلة. تقدم أوصافنا إرشادات موجزة. للقرارات الحاسمة، استشر متخصصًا.',
      q4_q: 'هل النتائج نهائية أو معتمدة؟',
      q4_a: 'لا. النتائج تقديرات بناءً على بياناتك وطريقتك المختارة. هي للأغراض الإعلامية/التعليمية فقط. تؤثر ظروف السوق والتفاصيل المحددة بشكل كبير على التقييمات الفعلية.',
      q5_q: 'هل يمكنني حفظ أو تصدير تقييمي؟',
      q5_a: 'توفر صفحة النتائج خيارات لتنزيل ملخص PDF أو طباعة التقرير. لا يتم حاليًا تنفيذ حفظ البيانات بالكامل إلى حساب.',
      q6_q: 'ما هي الافتراضات الرئيسية في التدفقات النقدية المخصومة (DCF)؟',
      q6_a: 'تشمل افتراضات DCF الرئيسية التدفقات النقدية الحرة المتوقعة (FCFs)، ومعدل الخصم (WACC - الذي يجب أن يعكس مخاطر الدولة والشركة المحددة)، ومعدل النمو النهائي. يمكنك إدخال علاوة مخاطر دولة بحثت عنها لإبلاغ WACC الخاص بك ومتوسط معدل نمو القطاع لإبلاغ التوقعات أو القيمة النهائية.',
      q7_q: 'أين يمكنني العثور على المعايير المالية؟',
      q7_a: "تتيح لك هذه المنصة إدخال المعايير التي بحثت عنها. للحصول على مصادر موثوقة، ضع في اعتبارك:\n- مزودي البيانات المالية (مثل Refinitiv، Bloomberg، FactSet غالبًا ما يكون لديهم ملخصات مجانية أو وصول تجريبي).\n- الموارد الأكاديمية مثل موقع أسواث داموداران (pages.stern.nyu.edu/~adamodar/) لبيانات عن علاوات المخاطر، بيتا، إلخ.\n- تقارير من البنوك الاستثمارية الكبرى، والشركات الاستشارية (مثل PwC، Deloitte، EY، McKinsey)، وجمعيات الصناعة.\n- وكالات الإحصاء الحكومية والبنوك المركزية للبيانات الاقتصادية وتقييمات مخاطر الدولة.\nتحقق دائمًا من ملاءمة البيانات وتاريخها ومنهجيتها. لا تقوم المنصة بجلب هذه البيانات تلقائيًا.",
      q8_q: 'كيف يتم استخدام المعايير المقدمة من المستخدم؟',
      q8_a: 'إذا قمت بإدخال معايير مثل متوسطات مضاعفات السعر إلى الأرباح للصناعة، أو مضاعفات قيمة المنشأة/الأرباح قبل الفوائد والضرائب، أو معدلات نمو القطاع، ستحاول المنصة استخدامها في طريقة التقييم ذات الصلة (مثل مضاعف السعر إلى الأرباح في المقارنات، نمو القطاع في القيمة النهائية للتدفقات النقدية المخصومة إذا كان ذلك ممكنًا). سيفصل تحليل الحساب في نتائجك كيف تم دمج أي معايير مقدمة. إذا لم تقدم، فقد تستخدم المنصة افتراضات أكثر عمومية لحساباتها التجريبية.',
    },
    footer: {
      copyright: `© ${new Date().getFullYear()} ${APP_NAME}. جميع الحقوق محفوظة. للأغراض التعليمية والتوضيحية فقط.`,
      contactName: 'الاسم: ياسر علي',
      contactMobile: 'الجوال: +966591715184',
      contactEmail: 'البريد الإلكتروني: y_ali41@hotmail.com',
      contactLinkedIn: 'www.linkedin.com/in/yaser-yousef-ali',
      contactLinkedInUrl: 'https://www.linkedin.com/in/yaser-yousef-ali'
    },
    common: {
      loading: 'Loading...', // Keep "Loading..." for simplicity, or "جار التحميل..."
      error: 'خطأ',
      noData: 'لا توجد بيانات متاحة',
      selectOption: 'اختر خيارا',
      details: 'تفاصيل',
      years: 'سنوات',
      percentageSymbol: '٪',
    }
  }
};
